version: '3.1'
services:

  # service:
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #     target: development
  #   volumes:
  #     - .:/usr/src/app
  #   env_file:
  #   - .env
  #   command: npm run start:debug
  #   ports:
  #     - 3000:3000
  #     - 9229:9229
  #   restart: unless-stopped

  dev-db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432

  test-db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: 123456
    ports:
      - 5434:5432

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

  zookeeper:
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    restart: unless-stopped
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'docker.io/bitnami/kafka:2-debian-10'
    restart: unless-stopped
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper

  mongo-dev:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456

  mongo-test:
    image: mongo
    restart: unless-stopped
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_MONGODB_URL: mongodb://root:123456@mongo-dev:27017/

  kafka-admin:
      image: 'docker.redpanda.com/vectorized/console:latest'
      restart: unless-stopped
      ports:
        - 8082:8080
      environment:
        - KAFKA_BROKERS=kafka:9092
      depends_on:
        - zookeeper
        - kafka

  redis:
    image: redis:6.2-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes