export const BOOKING_CLIENT_SERVICE = 'BOOKING_CLIENT_SERVICE';
export const DOCS_CLIENT_SERVICE = 'DOCS_CLIENT_SERVICE';
export const QUEUE_CLIENT_SERVICE = 'QUEUE_CLIENT_SERVICE';
export const IAM_CLIENT_SERVICE = 'IAM_CLIENT_SERVICE';
